# Generated by Django 4.1.3 on 2022-12-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_consumer_comment_recipe_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=69)),
                ('password', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='createdRecipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='savedRecipes',
            field=models.ManyToManyField(to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.user'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.AddField(
            model_name='admin',
            name='approvedRecipes',
            field=models.ManyToManyField(to='recipes.recipe'),
        ),
    ]
