# Generated by Django 4.1.4 on 2022-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeslug_remove_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='savedRecipes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
