# Generated by Django 4.1.4 on 2022-12-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_user_savedrecipes'),
        ('recipes', '0004_recipe_picture_alter_ingredient_name'),
    ]

    operations = [
    ]
